name: CI

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install ZFS
              run: sudo apt-get install zfsutils-linux libzfslinux-dev
            - name: Create a pool
              run: |
                sudo truncate -s 64M /testpool
                sudo zpool create tank /testpool
                zpool list
            - name: Setup OCaml
              uses: ocaml/setup-ocaml@v3
              with:
                ocaml-compiler: "5.1"
            - run: opam install . --deps-only --with-test
            - run: opam exec -- dune build
            - run: opam exec -- dune runtest
